apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-graf-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'node_rhel'
      static_configs:
      - targets: ['192.168.43.86:9100']
  
  datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://192.168.99.100:30002